#!/usr/bin/env python3
"""Revolve the existing 2D-axisymmetric Takahashi single-stage-cell profile
(from gen_takahashi.py's loop()) into a true 3D triangulated SPARTA surface,
for a first scoping test of a 3D version of the same, already-validated,
on-axis geometry.

Same physical dimensions as gen_takahashi.py (12.7mm ID cell, 53mm body,
4mm ID x 20mm inlet tube, 5mm aperture through a 0.5mm plate). This is NOT
yet the user's own asymmetric geometry (offset inlet) -- this is step 1:
get the 3D pipeline working and timed on the case we already have a solid
2D-axisymmetric reference result for.

Outward-normal convention: SPARTA triangles need normals pointing OUT of
the solid (right-hand rule N=(p2-p1)x(p3-p1)). For each 2D profile edge we
know the CORRECT outward 2D normal analytically (rotate the edge tangent
90 degrees, using the sign determined by the polygon's traversal direction
-- verified clockwise here via the shoelace formula, giving desired 2D
normal (Nx,Nr) = (-dr, dx) for edge tangent (dx,dr)). We generate each
candidate triangle, compute its actual geometric normal, and flip vertex
order if it disagrees with the analytically-known desired direction. This
sidesteps having to hand-derive a single global triangle-winding rule for
every edge case (frustum band vs. cone/apex).
"""
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# ---- paper geometry (Sec. III.A) -- identical to gen_takahashi.py ----
RCELL = 0.00635
CELL_LENGTH = 0.053
RB = 0.002
TUBE_LENGTH = 0.020
RAP = 0.0025
PLATE_THICK = 0.0005

XLO = -TUBE_LENGTH
XPLATE = CELL_LENGTH
XEXIT = XPLATE + PLATE_THICK
RTOP_GEOM = 55 * 1.3e-4

DX4 = 2.0e-4
XC = XLO + 1.5 * DX4 / 16
XOUT, ROUT = XLO - 0.0003, -0.0003

# ---- domain sizing, same as gen_takahashi.py ----
DR4 = 1.3e-4
DX1, DR1 = DX4 * 8.0, DR4 * 8.0
NY = 63
RTOP_DOMAIN = NY * DR1
NX = 109
XHI = XLO + NX * DX1

NTHETA = 24  # azimuthal segments -- coarse-but-round, fine for a scoping run

pts_raw = [(XEXIT, RTOP_GEOM), (XEXIT, RAP), (XPLATE, RAP), (XPLATE, RCELL), (0.0, RCELL),
           (0.0, RB), (XC, RB), (XC, ROUT), (XOUT, ROUT), (XOUT, RTOP_GEOM)]
types = [1, 1, 1, 1, 1, 1, 2, 1, 1, 1]
pts = [(x, max(r, 0.0)) for x, r in pts_raw]
N = len(pts)

points = []          # global list of (x,y,z), 0-indexed internally
point_index = {}     # (profile_vertex_i, theta_k) -> 1-based index into points


def get_ring_indices(i):
    x, r = pts[i]
    if r <= 0.0:
        key = (i, 0)
        if key not in point_index:
            points.append((x, 0.0, 0.0))
            point_index[key] = len(points)
        return [point_index[key]] * NTHETA
    idxs = []
    for k in range(NTHETA):
        key = (i, k)
        if key not in point_index:
            theta = 2 * math.pi * k / NTHETA
            points.append((x, r * math.cos(theta), r * math.sin(theta)))
            point_index[key] = len(points)
        idxs.append(point_index[key])
    return idxs


ring_cache = [get_ring_indices(i) for i in range(N)]

triangles = []  # (type, p1, p2, p3) 1-based


def cross(u, v):
    return (u[1] * v[2] - u[2] * v[1], u[2] * v[0] - u[0] * v[2], u[0] * v[1] - u[1] * v[0])


def sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


for i in range(N):
    j = (i + 1) % N
    x1, r1 = pts[i]
    x2, r2 = pts[j]
    if r1 <= 0.0 and r2 <= 0.0:
        continue  # degenerate on-axis edge, no real surface
    dx, dr = x2 - x1, r2 - r1
    Nx, Nr = -dr, dx  # desired outward 2D normal (clockwise-traversal formula, verified)
    ring1 = ring_cache[i]
    ring2 = ring_cache[j]
    ttype = types[i]
    for k in range(NTHETA):
        kk = (k + 1) % NTHETA
        a, b, c, d = ring1[k], ring1[kk], ring2[kk], ring2[k]
        theta_mid = 2 * math.pi * (k + 0.5) / NTHETA
        desired = (Nx, Nr * math.cos(theta_mid), Nr * math.sin(theta_mid))
        if r1 <= 0.0:
            candidates = [(a, d, c)]
        elif r2 <= 0.0:
            candidates = [(a, b, c)]
        else:
            candidates = [(a, b, c), (a, c, d)]
        for (p1, p2, p3) in candidates:
            if p1 == p2 or p2 == p3 or p1 == p3:
                continue
            P1, P2, P3 = points[p1 - 1], points[p2 - 1], points[p3 - 1]
            normal = cross(sub(P2, P1), sub(P3, P1))
            if dot(normal, desired) < 0:
                p2, p3 = p3, p2
            triangles.append((ttype, p1, p2, p3))

out_path = os.path.join(HERE, "cell_takahashi_3d.surf")
with open(out_path, "w", newline="\n") as f:
    f.write("# GENERATED by gen_takahashi_3d.py -- revolved Takahashi single-stage cell, true 3D.\n")
    f.write("# Same dimensions as gen_takahashi.py's 2D-axisymmetric profile, revolved %d-fold.\n" % NTHETA)
    f.write("# type 1 = wall, type 2 = inlet cap (mass-injection surface).\n\n")
    f.write("%d points\n%d triangles\n\n" % (len(points), len(triangles)))
    f.write("Points\n\n")
    for idx, (x, y, z) in enumerate(points, start=1):
        f.write("%d %.9g %.9g %.9g\n" % (idx, x, y, z))
    f.write("\nTriangles\n\n")
    for idx, (ttype, p1, p2, p3) in enumerate(triangles, start=1):
        f.write("%d %d %d %d %d\n" % (idx, ttype, p1, p2, p3))

print("wrote", out_path)
print("points:", len(points), " triangles:", len(triangles))
print("cap (type 2) triangles:", sum(1 for t in triangles if t[0] == 2))
print("domain: x [%.6g, %.6g] (%d cells @ %.4g um base), y=z [-%.6g, %.6g] (%d cells @ %.4g um base)"
      % (XLO, XHI, NX, DX1 * 1e6, RTOP_DOMAIN, RTOP_DOMAIN, 2 * NY, DR1 * 1e6))
