#!/usr/bin/env python3
"""Takahashi single-stage cell in true 3D, with the inlet tube shifted
off-axis -- a controlled test of whether an off-axis inlet by itself
produces the asymmetric exterior plume seen in cases/fluor-cell-3d.

Same dimensions as gen_takahashi_3d.py (12.7mm ID cell, 53mm body, 4mm ID
x 20mm inlet tube, 5mm aperture through a 0.5mm plate, solid outer body of
radius RTOP_GEOM). The only change: the inlet tube's axis is at y=Y_OFFSET
instead of on the cell axis, so the end wall at x=0 becomes a disc with an
off-center hole. Aperture stays on-axis.

Normals point OUT of the solid (into gas / into the exterior), as SPARTA
requires; each triangle is flipped if needed to agree with an analytically
known desired normal for its surface.
"""
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))

RCELL = 0.00635
CELL_LENGTH = 0.053
RB = 0.002
TUBE_LENGTH = 0.020
RAP = 0.0025
PLATE_THICK = 0.0005
RTOP_GEOM = 55 * 1.3e-4

XLO = -TUBE_LENGTH
XPLATE = CELL_LENGTH
XEXIT = XPLATE + PLATE_THICK
DX4 = 2.0e-4
XC = XLO + 1.5 * DX4 / 16
XOUT = XLO - 0.0003

Y_OFFSET = 0.003  # tube axis shift; hole edge stays 1.35mm inside the cell wall
assert Y_OFFSET + RB < RCELL

NTHETA = 48

points = []
triangles = []


def add_point(p):
    points.append(p)
    return len(points)


def ring(x, cy, r):
    return [add_point((x, cy + r * math.cos(2 * math.pi * k / NTHETA),
                       r * math.sin(2 * math.pi * k / NTHETA))) for k in range(NTHETA)]


def sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def cross(u, v):
    return (u[1] * v[2] - u[2] * v[1], u[2] * v[0] - u[0] * v[2], u[0] * v[1] - u[1] * v[0])


def dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def add_tri(ttype, p1, p2, p3, desired):
    P1, P2, P3 = points[p1 - 1], points[p2 - 1], points[p3 - 1]
    if dot(cross(sub(P2, P1), sub(P3, P1)), desired(P1, P2, P3)) < 0:
        p2, p3 = p3, p2
    triangles.append((ttype, p1, p2, p3))


def centroid(P1, P2, P3):
    return tuple((P1[i] + P2[i] + P3[i]) / 3 for i in range(3))


def radial(cy, sign):
    def f(P1, P2, P3):
        c = centroid(P1, P2, P3)
        return (0.0, sign * (c[1] - cy), sign * c[2])
    return f


def axial(sign):
    return lambda P1, P2, P3: (sign, 0.0, 0.0)


def band(r1, r2, desired, ttype=1):
    for k in range(NTHETA):
        kk = (k + 1) % NTHETA
        add_tri(ttype, r1[k], r1[kk], r2[kk], desired)
        add_tri(ttype, r1[k], r2[kk], r2[k], desired)


def fan(center, r, desired, ttype=1):
    for k in range(NTHETA):
        add_tri(ttype, center, r[k], r[(k + 1) % NTHETA], desired)


A = ring(XEXIT, 0.0, RTOP_GEOM)
B = ring(XEXIT, 0.0, RAP)
C = ring(XPLATE, 0.0, RAP)
D = ring(XPLATE, 0.0, RCELL)
E = ring(0.0, 0.0, RCELL)
F = ring(0.0, Y_OFFSET, RB)
G = ring(XC, Y_OFFSET, RB)
Gc = add_point((XC, Y_OFFSET, 0.0))
H = ring(XOUT, 0.0, RTOP_GEOM)
Hc = add_point((XOUT, 0.0, 0.0))

band(A, B, axial(+1))              # front face, faces exterior (+x)
band(B, C, radial(0.0, -1))        # aperture bore, faces the axis
band(C, D, axial(-1))              # plate inner face, faces the cell
band(D, E, radial(0.0, -1))        # cell wall
band(E, F, axial(+1))              # end wall with off-center hole, faces the cell
band(F, G, radial(Y_OFFSET, -1))   # inlet tube wall
fan(Gc, G, axial(+1), ttype=2)     # inlet cap: mass-injection surface
fan(Hc, H, axial(-1))              # back face, faces exterior (-x)
band(H, A, radial(0.0, +1))        # outer body cylinder

out_path = os.path.join(HERE, "cell_takahashi_3d_offset.surf")
with open(out_path, "w", newline="\n") as f:
    f.write("# GENERATED by gen_takahashi_3d_offset.py -- Takahashi cell, true 3D, inlet tube\n")
    f.write("# shifted off-axis by Y_OFFSET=%.4g m. type 1 = wall, type 2 = inlet cap.\n\n" % Y_OFFSET)
    f.write("%d points\n%d triangles\n\n" % (len(points), len(triangles)))
    f.write("Points\n\n")
    for idx, (x, y, z) in enumerate(points, start=1):
        f.write("%d %.9g %.9g %.9g\n" % (idx, x, y, z))
    f.write("\nTriangles\n\n")
    for idx, (ttype, p1, p2, p3) in enumerate(triangles, start=1):
        f.write("%d %d %d %d %d\n" % (idx, ttype, p1, p2, p3))

print("wrote", out_path, "points:", len(points), "triangles:", len(triangles),
      "cap:", sum(1 for t in triangles if t[0] == 2))
