#!/usr/bin/env python3
"""Generate the Takahashi single-stage cell and four transparent flux stations.

Dimensions from Takahashi, Shlivko, Woolls & Hutzler, "Simulation of cryogenic
buffer gas beams", Phys. Rev. Research 3, 023018 (2021), Sec. III.A:
12.7 mm body ID, 53 mm body length, 4 mm inlet-tube ID, 20 mm inlet-tube
length, 5 mm aperture diameter, 0.5 mm plate thickness. The inlet cap is a
reflecting 4 K surface with prescribed mass injection, same as the B5 case.

Unlike the B5 case (which truncates its inlet to a short "simulated feed
stub"), this case models the full 20 mm inlet tube length exactly as given
in the paper, since the paper does not describe a truncation.

Mesh: 3 refinement levels (simplified from B5's 5), each region spanning the
full radial extent so there are no internal radial refinement boundaries to
manage -- only axial ones. Each level-N band sits inside its level-(N-1)
parent by at least four level-(N-1) cells on every open (axial) side, per
the same nesting rule used in gen_b5.py, checked by tools/check_grid_2d.py.

Run from the repository root: python cases/takahashi-single/gen_takahashi.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# ---- paper geometry (Sec. III.A) ----
RCELL = 0.00635              # 12.7 mm ID / 2
CELL_LENGTH = 0.053          # 53 mm body length (tube/cell junction -> plate face)
RB = 0.002                   # 4 mm inlet tube ID / 2
TUBE_LENGTH = 0.020           # 20 mm inlet tube length (full length, not truncated)
RAP = 0.0025                  # 5 mm aperture diameter / 2 (same as B5)
PLATE_THICK = 0.0005          # 0.5 mm plate thickness

XLO = -TUBE_LENGTH            # -0.020
XPLATE = CELL_LENGTH          # 0.053, plate cell-side face
XEXIT = XPLATE + PLATE_THICK  # 0.0535, channel exit

# ---- mesh: base cell + 3 refinement levels ----
DX1 = 2.0e-4                  # 200 um base axial cell
DR1 = 1.3e-4                   # 130 um base radial cell (~49 cells across cell radius; not an exact divisor of RCELL, so RCELL doesn't land on a cell face)
NY = 55                       # RTOP = 55 * DR1 ~= 10% margin above RCELL
RTOP = NY * DR1
NX = 506                      # domain axial extent; ~27.6 mm plume region past XEXIT (matches B5)
XHI = XLO + NX * DX1

DX2, DR2 = DX1 / 2.0, DR1 / 2.0     # L2: 100 x 63.5 um
DX3, DR3 = DX1 / 4.0, DR1 / 4.0     # L3: 50 x 31.75 um

# L2 band: tube/cell junction through the whole cell body (full radius)
L2_XLO, L2_XHI = -0.003, 0.057
# L3 band: the plate/throat region (full radius)
L3_XLO, L3_XHI = 0.051, 0.0555

# ---- station / cap coordinates ----
XC = XLO + 1.5 * DX1 / 16        # cap: just inside xlo, non-face at L1
XTUBE = -0.0013 - 1.5 * DX2 / 16  # tube station, within the L2 band (nudged off-face)
XAP = 0.05325 - 1.5 * DX3 / 16    # aperture station, within the L3 band (mid-plate, nudged off-face)
R_TUBE_ST = RB + 0.0006          # through the tube wall into "solid"
R_AP_ST = RAP + 0.0013           # through the channel wall into the plate
XOUT, ROUT = XLO - 0.0003, -0.0003


def nonface(name, coord, origin, base, finest_level):
    for lev in range(1, finest_level + 1):
        h = base / 2 ** (lev - 1)
        idx = (coord - origin) / h
        assert abs(idx - round(idx)) > 1e-6, "%s on a cell face at L%d (index %.4f)" % (name, lev, idx)
    print("%-8s %.7g  non-face down to L%d (%.3g um)" % (name, coord, finest_level, base / 2 ** (finest_level - 1) * 1e6))


def station(x, rtop, tag, fwd):
    p = [(x, 0.0), (x, rtop)] if fwd else [(x, rtop), (x, 0.0)]
    hdr = "# GENERATED by gen_takahashi.py. %s station at x = %.7g, %s movers (p1->p2 %s)." % (
        tag, x, "+x" if fwd else "-x", "+r" if fwd else "-r")
    return "\n".join([hdr, "", "2 points", "1 lines", "", "Points", "",
                      "1 %.9g %.9g" % p[0], "2 %.9g %.9g" % p[1], "", "Lines", "", "1 1 2", ""])


def loop():
    pts = [(XEXIT, RTOP), (XEXIT, RAP), (XPLATE, RAP), (XPLATE, RCELL), (0.0, RCELL),
           (0.0, RB), (XC, RB), (XC, ROUT), (XOUT, ROUT), (XOUT, RTOP)]
    types = [1, 1, 1, 1, 1, 1, 2, 1, 1, 1]
    n = len(pts)
    out = ["# GENERATED by gen_takahashi.py -- Takahashi et al. (2021) single-stage cell, 2D axisymmetric.",
           "# 12.7 x 53 mm body, 5 mm aperture through 0.5 mm plate (%.6g-%.6g)," % (XPLATE, XEXIT),
           "# 4 mm ID x 20 mm inlet tube, CAP (type 2) at x = %.7g, normal +x." % XC,
           "# type 1 = every wall; read with `type group cellwalls clip`, then `group cap surf type 2`.",
           "", "%d points" % n, "%d lines" % n, "", "Points", ""]
    out += ["%d %.9g %.9g" % (i + 1, x, y) for i, (x, y) in enumerate(pts)]
    out += ["", "Lines", ""]
    out += ["%d %d %d %d" % (i + 1, types[i], i + 1, (i + 1) % n + 1) for i in range(n)]
    out.append("")
    return "\n".join(out)


def main():
    nonface("cap x", XC, XLO, DX1, 1)
    nonface("bore r", RB, 0.0, DR1, 2)
    nonface("tube st", XTUBE, XLO, DX1, 2)
    nonface("ap st", XAP, XLO, DX1, 3)
    nonface("r_cell", RCELL, 0.0, DR1, 3)
    nonface("r_ap", RAP, 0.0, DR1, 3)
    for name, text in {
        "cell_takahashi.surf": loop(),
        "tube_fwd.surf": station(XTUBE, R_TUBE_ST, "tube", True),
        "tube_rev.surf": station(XTUBE, R_TUBE_ST, "tube", False),
        "ap_fwd.surf": station(XAP, R_AP_ST, "aperture", True),
        "ap_rev.surf": station(XAP, R_AP_ST, "aperture", False),
    }.items():
        with open(os.path.join(HERE, name), "w", newline="\n") as f:
            f.write(text)
        print("wrote", name)
    print("domain: x [%.6g, %.6g] (%d cells @ %.4g um), r [0, %.6g] (%d cells @ %.4g um)"
          % (XLO, XHI, NX, DX1 * 1e6, RTOP, NY, DR1 * 1e6))
    sccm = 20.0  # matches the paper's Fig. 1 example flow rate
    ndot = sccm * 4.478e17
    mdot = ndot * 6.6464791e-27
    fill = 4 * ndot / (1.07 * 145.5 * 3.141592653589793 * RAP ** 2)
    print("%.0f SCCM: Mdot = %.6e kg/s, aperture-law fill n = %.4e m^-3" % (sccm, mdot, fill))


if __name__ == "__main__":
    main()
