import json, numpy as np
kB = 8314.46; m, M = 20.1797, 156.325; mu = m*M/(m+M)
d = json.load(open("ion_curve4.json")); E = np.array(d["E"])
keys = {"central": "central(ra=1.5)", "low": "soft(ra=1.2,x0.5)", "high": "stiff(ra=1.8,x2)"}
def Q1fun(key):
    lE, lQ = np.log(E), np.log(np.array(d[key])*1e-20); s0 = (lQ[1]-lQ[0])/(lE[1]-lE[0])
    return lambda Ek: np.exp(np.where(np.log(Ek) < lE[0], lQ[0] + s0*(np.log(Ek)-lE[0]), np.interp(np.log(Ek), lE, lQ)))
x = np.linspace(1e-4, 40, 8000)
def rest_limit(T, key):          # exact V->0 value: sigma_bar(T) * gbar / vref, at E_cm = mu vref^2 / 2
    sb = 0.5*np.trapz(x**2*np.exp(-x)*Q1fun(key)(x*T), x)
    return sb*np.sqrt(8*kB*T/(np.pi*mu))/np.sqrt(8*kB*T/(np.pi*m))
Ec0 = lambda T: mu*(8*kB*T/(np.pi*m))/(2*kB)
t = json.load(open("tracer_sigma_t.json")); Ec = np.array(t["Ec"])
rows = []
for T in np.geomspace(1.0, 23.0, 14):                       # V = 0 at colder local T (exact)
    rows.append((Ec0(T), *[rest_limit(T, k) for k in keys.values()]))
keep = np.where(Ec > Ec0(23.0)*1.08)[0]                        # drop the noisy near-zero-V MC points
for i in keep:
    rows.append((Ec[i], *[t[k][i] for k in keys]))
rows.sort()
hdr = """# BaF+ - Ne TRACER-EFFECTIVE cross section sigma_t(E_cm) for ParticleTracing3D.jl (--sigma-model table).
# NOT the bare momentum-transfer cross section: the tracer draws collisions at rate n*sigma*v_coll with a
# flux-weighted Maxwellian partner and isotropic CM scattering, so sigma_t is defined such that the
# tracer's mean drag force on an ion moving at speed V equals the true drag from Q1(g):
#     sigma_t(V) = <Q1(g) g g_par> <g> / (v_coll <g g_par>),  averages over the Ne Maxwellian,
# tabulated against E_cm = mu*v_coll^2/2 with v_coll = sqrt(8kT/(pi m_Ne) + V^2) (what the tracer computes).
# -> equals Q1 for fast ions (>~1.5 km/s), and the Chapman-Enskog thermal value at rest, so both the
#    500 eV slowing-down and the thermal diffusion coefficient are reproduced.
# Rows with E_cm < 25.9 K: exact V=0 limit for local T = 1-23 K. Rows above: computed at T = 23 K
#    (T-independent for fast ions; approximate at intermediate speeds if the local T differs from 23 K).
# Q1(E) itself: classical, Ba+-Ne proxy potential = CCSD(T)/CBS Ba+-Ne of Buchachenko & Viehland,
#    J. Chem. Phys. 148, 154304 (2018) (sigma0 3.254 A, Re 4.267 A, De 75.0 cm^-1, C4 = alpha_Ne/2)
#    for r >= 2.9 A, ZBL universal repulsion inside; checks: 1.105 x Langevin limit, ZBL/SRIM nuclear
#    stopping at 100-500 eV lab within 2-15%.  low/high = soft/stiff short-range wall variants.
# Generated by tools/cross_section/{ion4.py, tracer_table.py, write_tracer_table.py}.
# E_cm_K\tsigma_central_m2\tsigma_low_m2\tsigma_high_m2
"""
with open("bafplus_ne_sigma_tracer.tsv", "w") as f:
    f.write(hdr)
    for r in rows: f.write("%.6e\t%.6e\t%.6e\t%.6e\n" % r)
arr = np.array(rows)
print(len(rows), "rows; E range %.3g-%.3g K" % (arr[0,0], arr[-1,0]))
print("monotonic non-increasing central:", bool(np.all(np.diff(arr[:,1]) <= 1e-21)))
for e in [1.13, 10, 25.94, 30, 100, 300, 1e3, 1e4, 1e5, 6.63e5]:
    print(f"  E={e:9.3g} K  sigma_t={np.exp(np.interp(np.log(e), np.log(arr[:,0]), np.log(arr[:,1]))):.3e}")
